/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ApplyRouteRouteImport } from './routes/apply/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as OrgsIndexRouteImport } from './routes/orgs/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as ApplyIndexRouteImport } from './routes/apply/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileAttendanceRouteImport } from './routes/profile/attendance'
import { Route as ProfileAgentRouteImport } from './routes/profile/agent'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities/$id'
import { Route as MatchesIdRouteImport } from './routes/matches/$id'
import { Route as ApplyStatusRouteImport } from './routes/apply/status'
import { Route as AdminUsersRouteRouteImport } from './routes/admin/users/route'
import { Route as AdminApplicationsRouteRouteImport } from './routes/admin/applications/route'
import { Route as OrgSlugIndexRouteImport } from './routes/org/$slug/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminOpportunitiesIndexRouteImport } from './routes/admin/opportunities/index'
import { Route as AdminCostsIndexRouteImport } from './routes/admin/costs/index'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin/applications/index'
import { Route as OrgSlugVisitRouteImport } from './routes/org/$slug/visit'
import { Route as OrgSlugProgramsRouteImport } from './routes/org/$slug/programs'
import { Route as OrgSlugJoinRouteImport } from './routes/org/$slug/join'
import { Route as OrgSlugEventsRouteImport } from './routes/org/$slug/events'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminOpportunitiesNewRouteImport } from './routes/admin/opportunities/new'
import { Route as OrgSlugAdminRouteRouteImport } from './routes/org/$slug/admin/route'
import { Route as OrgSlugSpaceIndexRouteImport } from './routes/org/$slug/space/index'
import { Route as OrgSlugAdminIndexRouteImport } from './routes/org/$slug/admin/index'
import { Route as OrgSlugSpaceBookingsRouteImport } from './routes/org/$slug/space/bookings'
import { Route as OrgSlugProgramProgramSlugRouteImport } from './routes/org/$slug/program/$programSlug'
import { Route as OrgSlugApplyOpportunityIdRouteImport } from './routes/org/$slug/apply/$opportunityId'
import { Route as OrgSlugAdminSpaceRouteImport } from './routes/org/$slug/admin/space'
import { Route as OrgSlugAdminSetupRouteImport } from './routes/org/$slug/admin/setup'
import { Route as OrgSlugAdminSettingsRouteImport } from './routes/org/$slug/admin/settings'
import { Route as OrgSlugAdminGuestsRouteImport } from './routes/org/$slug/admin/guests'
import { Route as OrgSlugAdminBookingsRouteImport } from './routes/org/$slug/admin/bookings'
import { Route as AdminOpportunitiesIdEditRouteImport } from './routes/admin/opportunities/$id/edit'
import { Route as OrgSlugSurveySurveyTokenIndexRouteImport } from './routes/org/$slug/survey/$surveyToken/index'
import { Route as OrgSlugPollPollTokenIndexRouteImport } from './routes/org/$slug/poll/$pollToken/index'
import { Route as OrgSlugAdminProgramsIndexRouteImport } from './routes/org/$slug/admin/programs/index'
import { Route as OrgSlugAdminOpportunitiesIndexRouteImport } from './routes/org/$slug/admin/opportunities/index'
import { Route as OrgSlugAdminMembersIndexRouteImport } from './routes/org/$slug/admin/members/index'
import { Route as OrgSlugAdminCrmIndexRouteImport } from './routes/org/$slug/admin/crm/index'
import { Route as OrgSlugAdminApplicationsIndexRouteImport } from './routes/org/$slug/admin/applications/index'
import { Route as OrgSlugSurveySurveyTokenRespondentTokenRouteImport } from './routes/org/$slug/survey/$surveyToken/$respondentToken'
import { Route as OrgSlugPollPollTokenRespondentTokenRouteImport } from './routes/org/$slug/poll/$pollToken/$respondentToken'
import { Route as OrgSlugAdminMembersUserIdRouteImport } from './routes/org/$slug/admin/members/$userId'
import { Route as OrgSlugAdminProgramsProgramIdIndexRouteImport } from './routes/org/$slug/admin/programs/$programId/index'
import { Route as OrgSlugAdminOpportunitiesOppIdIndexRouteImport } from './routes/org/$slug/admin/opportunities/$oppId/index'
import { Route as OrgSlugAdminProgramsProgramIdSessionRunnerRouteImport } from './routes/org/$slug/admin/programs/$programId/session-runner'
import { Route as OrgSlugAdminOpportunitiesOppIdEmailRouteImport } from './routes/org/$slug/admin/opportunities/$oppId/email'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRouteRoute = ApplyRouteRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsIndexRoute = OrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIndexRoute = ApplyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplyRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAttendanceRoute = ProfileAttendanceRouteImport.update({
  id: '/profile/attendance',
  path: '/profile/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAgentRoute = ProfileAgentRouteImport.update({
  id: '/profile/agent',
  path: '/profile/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyStatusRoute = ApplyStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApplyRouteRoute,
} as any)
const AdminUsersRouteRoute = AdminUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsRouteRoute = AdminApplicationsRouteRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/org/$slug/',
  path: '/org/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRouteRoute,
} as any)
const AdminOpportunitiesIndexRoute = AdminOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCostsIndexRoute = AdminCostsIndexRouteImport.update({
  id: '/costs/',
  path: '/costs/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminApplicationsRouteRoute,
} as any)
const OrgSlugVisitRoute = OrgSlugVisitRouteImport.update({
  id: '/org/$slug/visit',
  path: '/org/$slug/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugProgramsRoute = OrgSlugProgramsRouteImport.update({
  id: '/org/$slug/programs',
  path: '/org/$slug/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugJoinRoute = OrgSlugJoinRouteImport.update({
  id: '/org/$slug/join',
  path: '/org/$slug/join',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugEventsRoute = OrgSlugEventsRouteImport.update({
  id: '/org/$slug/events',
  path: '/org/$slug/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRouteRoute,
} as any)
const AdminOpportunitiesNewRoute = AdminOpportunitiesNewRouteImport.update({
  id: '/opportunities/new',
  path: '/opportunities/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrgSlugAdminRouteRoute = OrgSlugAdminRouteRouteImport.update({
  id: '/org/$slug/admin',
  path: '/org/$slug/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugSpaceIndexRoute = OrgSlugSpaceIndexRouteImport.update({
  id: '/org/$slug/space/',
  path: '/org/$slug/space/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAdminIndexRoute = OrgSlugAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugAdminRouteRoute,
} as any)
const OrgSlugSpaceBookingsRoute = OrgSlugSpaceBookingsRouteImport.update({
  id: '/org/$slug/space/bookings',
  path: '/org/$slug/space/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugProgramProgramSlugRoute =
  OrgSlugProgramProgramSlugRouteImport.update({
    id: '/org/$slug/program/$programSlug',
    path: '/org/$slug/program/$programSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgSlugApplyOpportunityIdRoute =
  OrgSlugApplyOpportunityIdRouteImport.update({
    id: '/org/$slug/apply/$opportunityId',
    path: '/org/$slug/apply/$opportunityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgSlugAdminSpaceRoute = OrgSlugAdminSpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => OrgSlugAdminRouteRoute,
} as any)
const OrgSlugAdminSetupRoute = OrgSlugAdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => OrgSlugAdminRouteRoute,
} as any)
const OrgSlugAdminSettingsRoute = OrgSlugAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugAdminRouteRoute,
} as any)
const OrgSlugAdminGuestsRoute = OrgSlugAdminGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => OrgSlugAdminRouteRoute,
} as any)
const OrgSlugAdminBookingsRoute = OrgSlugAdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => OrgSlugAdminRouteRoute,
} as any)
const AdminOpportunitiesIdEditRoute =
  AdminOpportunitiesIdEditRouteImport.update({
    id: '/opportunities/$id/edit',
    path: '/opportunities/$id/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const OrgSlugSurveySurveyTokenIndexRoute =
  OrgSlugSurveySurveyTokenIndexRouteImport.update({
    id: '/org/$slug/survey/$surveyToken/',
    path: '/org/$slug/survey/$surveyToken/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgSlugPollPollTokenIndexRoute =
  OrgSlugPollPollTokenIndexRouteImport.update({
    id: '/org/$slug/poll/$pollToken/',
    path: '/org/$slug/poll/$pollToken/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgSlugAdminProgramsIndexRoute =
  OrgSlugAdminProgramsIndexRouteImport.update({
    id: '/programs/',
    path: '/programs/',
    getParentRoute: () => OrgSlugAdminRouteRoute,
  } as any)
const OrgSlugAdminOpportunitiesIndexRoute =
  OrgSlugAdminOpportunitiesIndexRouteImport.update({
    id: '/opportunities/',
    path: '/opportunities/',
    getParentRoute: () => OrgSlugAdminRouteRoute,
  } as any)
const OrgSlugAdminMembersIndexRoute =
  OrgSlugAdminMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => OrgSlugAdminRouteRoute,
  } as any)
const OrgSlugAdminCrmIndexRoute = OrgSlugAdminCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => OrgSlugAdminRouteRoute,
} as any)
const OrgSlugAdminApplicationsIndexRoute =
  OrgSlugAdminApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => OrgSlugAdminRouteRoute,
  } as any)
const OrgSlugSurveySurveyTokenRespondentTokenRoute =
  OrgSlugSurveySurveyTokenRespondentTokenRouteImport.update({
    id: '/org/$slug/survey/$surveyToken/$respondentToken',
    path: '/org/$slug/survey/$surveyToken/$respondentToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgSlugPollPollTokenRespondentTokenRoute =
  OrgSlugPollPollTokenRespondentTokenRouteImport.update({
    id: '/org/$slug/poll/$pollToken/$respondentToken',
    path: '/org/$slug/poll/$pollToken/$respondentToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgSlugAdminMembersUserIdRoute =
  OrgSlugAdminMembersUserIdRouteImport.update({
    id: '/members/$userId',
    path: '/members/$userId',
    getParentRoute: () => OrgSlugAdminRouteRoute,
  } as any)
const OrgSlugAdminProgramsProgramIdIndexRoute =
  OrgSlugAdminProgramsProgramIdIndexRouteImport.update({
    id: '/programs/$programId/',
    path: '/programs/$programId/',
    getParentRoute: () => OrgSlugAdminRouteRoute,
  } as any)
const OrgSlugAdminOpportunitiesOppIdIndexRoute =
  OrgSlugAdminOpportunitiesOppIdIndexRouteImport.update({
    id: '/opportunities/$oppId/',
    path: '/opportunities/$oppId/',
    getParentRoute: () => OrgSlugAdminRouteRoute,
  } as any)
const OrgSlugAdminProgramsProgramIdSessionRunnerRoute =
  OrgSlugAdminProgramsProgramIdSessionRunnerRouteImport.update({
    id: '/programs/$programId/session-runner',
    path: '/programs/$programId/session-runner',
    getParentRoute: () => OrgSlugAdminRouteRoute,
  } as any)
const OrgSlugAdminOpportunitiesOppIdEmailRoute =
  OrgSlugAdminOpportunitiesOppIdEmailRouteImport.update({
    id: '/opportunities/$oppId/email',
    path: '/opportunities/$oppId/email',
    getParentRoute: () => OrgSlugAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/apply': typeof ApplyRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/applications': typeof AdminApplicationsRouteRouteWithChildren
  '/admin/users': typeof AdminUsersRouteRouteWithChildren
  '/apply/status': typeof ApplyStatusRoute
  '/matches/$id': typeof MatchesIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/profile/agent': typeof ProfileAgentRoute
  '/profile/attendance': typeof ProfileAttendanceRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/org/$slug/admin': typeof OrgSlugAdminRouteRouteWithChildren
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/org/$slug/events': typeof OrgSlugEventsRoute
  '/org/$slug/join': typeof OrgSlugJoinRoute
  '/org/$slug/programs': typeof OrgSlugProgramsRoute
  '/org/$slug/visit': typeof OrgSlugVisitRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/costs/': typeof AdminCostsIndexRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/admin/opportunities/$id/edit': typeof AdminOpportunitiesIdEditRoute
  '/org/$slug/admin/bookings': typeof OrgSlugAdminBookingsRoute
  '/org/$slug/admin/guests': typeof OrgSlugAdminGuestsRoute
  '/org/$slug/admin/settings': typeof OrgSlugAdminSettingsRoute
  '/org/$slug/admin/setup': typeof OrgSlugAdminSetupRoute
  '/org/$slug/admin/space': typeof OrgSlugAdminSpaceRoute
  '/org/$slug/apply/$opportunityId': typeof OrgSlugApplyOpportunityIdRoute
  '/org/$slug/program/$programSlug': typeof OrgSlugProgramProgramSlugRoute
  '/org/$slug/space/bookings': typeof OrgSlugSpaceBookingsRoute
  '/org/$slug/admin/': typeof OrgSlugAdminIndexRoute
  '/org/$slug/space/': typeof OrgSlugSpaceIndexRoute
  '/org/$slug/admin/members/$userId': typeof OrgSlugAdminMembersUserIdRoute
  '/org/$slug/poll/$pollToken/$respondentToken': typeof OrgSlugPollPollTokenRespondentTokenRoute
  '/org/$slug/survey/$surveyToken/$respondentToken': typeof OrgSlugSurveySurveyTokenRespondentTokenRoute
  '/org/$slug/admin/applications/': typeof OrgSlugAdminApplicationsIndexRoute
  '/org/$slug/admin/crm/': typeof OrgSlugAdminCrmIndexRoute
  '/org/$slug/admin/members/': typeof OrgSlugAdminMembersIndexRoute
  '/org/$slug/admin/opportunities/': typeof OrgSlugAdminOpportunitiesIndexRoute
  '/org/$slug/admin/programs/': typeof OrgSlugAdminProgramsIndexRoute
  '/org/$slug/poll/$pollToken/': typeof OrgSlugPollPollTokenIndexRoute
  '/org/$slug/survey/$surveyToken/': typeof OrgSlugSurveySurveyTokenIndexRoute
  '/org/$slug/admin/opportunities/$oppId/email': typeof OrgSlugAdminOpportunitiesOppIdEmailRoute
  '/org/$slug/admin/programs/$programId/session-runner': typeof OrgSlugAdminProgramsProgramIdSessionRunnerRoute
  '/org/$slug/admin/opportunities/$oppId/': typeof OrgSlugAdminOpportunitiesOppIdIndexRoute
  '/org/$slug/admin/programs/$programId/': typeof OrgSlugAdminProgramsProgramIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/apply/status': typeof ApplyStatusRoute
  '/matches/$id': typeof MatchesIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/profile/agent': typeof ProfileAgentRoute
  '/profile/attendance': typeof ProfileAttendanceRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin': typeof AdminIndexRoute
  '/apply': typeof ApplyIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/orgs': typeof OrgsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/org/$slug/events': typeof OrgSlugEventsRoute
  '/org/$slug/join': typeof OrgSlugJoinRoute
  '/org/$slug/programs': typeof OrgSlugProgramsRoute
  '/org/$slug/visit': typeof OrgSlugVisitRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/costs': typeof AdminCostsIndexRoute
  '/admin/opportunities': typeof AdminOpportunitiesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/org/$slug': typeof OrgSlugIndexRoute
  '/admin/opportunities/$id/edit': typeof AdminOpportunitiesIdEditRoute
  '/org/$slug/admin/bookings': typeof OrgSlugAdminBookingsRoute
  '/org/$slug/admin/guests': typeof OrgSlugAdminGuestsRoute
  '/org/$slug/admin/settings': typeof OrgSlugAdminSettingsRoute
  '/org/$slug/admin/setup': typeof OrgSlugAdminSetupRoute
  '/org/$slug/admin/space': typeof OrgSlugAdminSpaceRoute
  '/org/$slug/apply/$opportunityId': typeof OrgSlugApplyOpportunityIdRoute
  '/org/$slug/program/$programSlug': typeof OrgSlugProgramProgramSlugRoute
  '/org/$slug/space/bookings': typeof OrgSlugSpaceBookingsRoute
  '/org/$slug/admin': typeof OrgSlugAdminIndexRoute
  '/org/$slug/space': typeof OrgSlugSpaceIndexRoute
  '/org/$slug/admin/members/$userId': typeof OrgSlugAdminMembersUserIdRoute
  '/org/$slug/poll/$pollToken/$respondentToken': typeof OrgSlugPollPollTokenRespondentTokenRoute
  '/org/$slug/survey/$surveyToken/$respondentToken': typeof OrgSlugSurveySurveyTokenRespondentTokenRoute
  '/org/$slug/admin/applications': typeof OrgSlugAdminApplicationsIndexRoute
  '/org/$slug/admin/crm': typeof OrgSlugAdminCrmIndexRoute
  '/org/$slug/admin/members': typeof OrgSlugAdminMembersIndexRoute
  '/org/$slug/admin/opportunities': typeof OrgSlugAdminOpportunitiesIndexRoute
  '/org/$slug/admin/programs': typeof OrgSlugAdminProgramsIndexRoute
  '/org/$slug/poll/$pollToken': typeof OrgSlugPollPollTokenIndexRoute
  '/org/$slug/survey/$surveyToken': typeof OrgSlugSurveySurveyTokenIndexRoute
  '/org/$slug/admin/opportunities/$oppId/email': typeof OrgSlugAdminOpportunitiesOppIdEmailRoute
  '/org/$slug/admin/programs/$programId/session-runner': typeof OrgSlugAdminProgramsProgramIdSessionRunnerRoute
  '/org/$slug/admin/opportunities/$oppId': typeof OrgSlugAdminOpportunitiesOppIdIndexRoute
  '/org/$slug/admin/programs/$programId': typeof OrgSlugAdminProgramsProgramIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/apply': typeof ApplyRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/applications': typeof AdminApplicationsRouteRouteWithChildren
  '/admin/users': typeof AdminUsersRouteRouteWithChildren
  '/apply/status': typeof ApplyStatusRoute
  '/matches/$id': typeof MatchesIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/profile/agent': typeof ProfileAgentRoute
  '/profile/attendance': typeof ProfileAttendanceRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin/': typeof AdminIndexRoute
  '/apply/': typeof ApplyIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/orgs/': typeof OrgsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/org/$slug/admin': typeof OrgSlugAdminRouteRouteWithChildren
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/org/$slug/events': typeof OrgSlugEventsRoute
  '/org/$slug/join': typeof OrgSlugJoinRoute
  '/org/$slug/programs': typeof OrgSlugProgramsRoute
  '/org/$slug/visit': typeof OrgSlugVisitRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/costs/': typeof AdminCostsIndexRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/org/$slug/': typeof OrgSlugIndexRoute
  '/admin/opportunities/$id/edit': typeof AdminOpportunitiesIdEditRoute
  '/org/$slug/admin/bookings': typeof OrgSlugAdminBookingsRoute
  '/org/$slug/admin/guests': typeof OrgSlugAdminGuestsRoute
  '/org/$slug/admin/settings': typeof OrgSlugAdminSettingsRoute
  '/org/$slug/admin/setup': typeof OrgSlugAdminSetupRoute
  '/org/$slug/admin/space': typeof OrgSlugAdminSpaceRoute
  '/org/$slug/apply/$opportunityId': typeof OrgSlugApplyOpportunityIdRoute
  '/org/$slug/program/$programSlug': typeof OrgSlugProgramProgramSlugRoute
  '/org/$slug/space/bookings': typeof OrgSlugSpaceBookingsRoute
  '/org/$slug/admin/': typeof OrgSlugAdminIndexRoute
  '/org/$slug/space/': typeof OrgSlugSpaceIndexRoute
  '/org/$slug/admin/members/$userId': typeof OrgSlugAdminMembersUserIdRoute
  '/org/$slug/poll/$pollToken/$respondentToken': typeof OrgSlugPollPollTokenRespondentTokenRoute
  '/org/$slug/survey/$surveyToken/$respondentToken': typeof OrgSlugSurveySurveyTokenRespondentTokenRoute
  '/org/$slug/admin/applications/': typeof OrgSlugAdminApplicationsIndexRoute
  '/org/$slug/admin/crm/': typeof OrgSlugAdminCrmIndexRoute
  '/org/$slug/admin/members/': typeof OrgSlugAdminMembersIndexRoute
  '/org/$slug/admin/opportunities/': typeof OrgSlugAdminOpportunitiesIndexRoute
  '/org/$slug/admin/programs/': typeof OrgSlugAdminProgramsIndexRoute
  '/org/$slug/poll/$pollToken/': typeof OrgSlugPollPollTokenIndexRoute
  '/org/$slug/survey/$surveyToken/': typeof OrgSlugSurveySurveyTokenIndexRoute
  '/org/$slug/admin/opportunities/$oppId/email': typeof OrgSlugAdminOpportunitiesOppIdEmailRoute
  '/org/$slug/admin/programs/$programId/session-runner': typeof OrgSlugAdminProgramsProgramIdSessionRunnerRoute
  '/org/$slug/admin/opportunities/$oppId/': typeof OrgSlugAdminOpportunitiesOppIdIndexRoute
  '/org/$slug/admin/programs/$programId/': typeof OrgSlugAdminProgramsProgramIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/settings'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/admin/applications'
    | '/admin/users'
    | '/apply/status'
    | '/matches/$id'
    | '/opportunities/$id'
    | '/profile/agent'
    | '/profile/attendance'
    | '/profile/edit'
    | '/admin/'
    | '/apply/'
    | '/matches/'
    | '/opportunities/'
    | '/orgs/'
    | '/profile/'
    | '/settings/'
    | '/org/$slug/admin'
    | '/admin/opportunities/new'
    | '/admin/users/$userId'
    | '/org/$slug/events'
    | '/org/$slug/join'
    | '/org/$slug/programs'
    | '/org/$slug/visit'
    | '/admin/applications/'
    | '/admin/costs/'
    | '/admin/opportunities/'
    | '/admin/users/'
    | '/org/$slug/'
    | '/admin/opportunities/$id/edit'
    | '/org/$slug/admin/bookings'
    | '/org/$slug/admin/guests'
    | '/org/$slug/admin/settings'
    | '/org/$slug/admin/setup'
    | '/org/$slug/admin/space'
    | '/org/$slug/apply/$opportunityId'
    | '/org/$slug/program/$programSlug'
    | '/org/$slug/space/bookings'
    | '/org/$slug/admin/'
    | '/org/$slug/space/'
    | '/org/$slug/admin/members/$userId'
    | '/org/$slug/poll/$pollToken/$respondentToken'
    | '/org/$slug/survey/$surveyToken/$respondentToken'
    | '/org/$slug/admin/applications/'
    | '/org/$slug/admin/crm/'
    | '/org/$slug/admin/members/'
    | '/org/$slug/admin/opportunities/'
    | '/org/$slug/admin/programs/'
    | '/org/$slug/poll/$pollToken/'
    | '/org/$slug/survey/$surveyToken/'
    | '/org/$slug/admin/opportunities/$oppId/email'
    | '/org/$slug/admin/programs/$programId/session-runner'
    | '/org/$slug/admin/opportunities/$oppId/'
    | '/org/$slug/admin/programs/$programId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/apply/status'
    | '/matches/$id'
    | '/opportunities/$id'
    | '/profile/agent'
    | '/profile/attendance'
    | '/profile/edit'
    | '/admin'
    | '/apply'
    | '/matches'
    | '/opportunities'
    | '/orgs'
    | '/profile'
    | '/settings'
    | '/admin/opportunities/new'
    | '/admin/users/$userId'
    | '/org/$slug/events'
    | '/org/$slug/join'
    | '/org/$slug/programs'
    | '/org/$slug/visit'
    | '/admin/applications'
    | '/admin/costs'
    | '/admin/opportunities'
    | '/admin/users'
    | '/org/$slug'
    | '/admin/opportunities/$id/edit'
    | '/org/$slug/admin/bookings'
    | '/org/$slug/admin/guests'
    | '/org/$slug/admin/settings'
    | '/org/$slug/admin/setup'
    | '/org/$slug/admin/space'
    | '/org/$slug/apply/$opportunityId'
    | '/org/$slug/program/$programSlug'
    | '/org/$slug/space/bookings'
    | '/org/$slug/admin'
    | '/org/$slug/space'
    | '/org/$slug/admin/members/$userId'
    | '/org/$slug/poll/$pollToken/$respondentToken'
    | '/org/$slug/survey/$surveyToken/$respondentToken'
    | '/org/$slug/admin/applications'
    | '/org/$slug/admin/crm'
    | '/org/$slug/admin/members'
    | '/org/$slug/admin/opportunities'
    | '/org/$slug/admin/programs'
    | '/org/$slug/poll/$pollToken'
    | '/org/$slug/survey/$surveyToken'
    | '/org/$slug/admin/opportunities/$oppId/email'
    | '/org/$slug/admin/programs/$programId/session-runner'
    | '/org/$slug/admin/opportunities/$oppId'
    | '/org/$slug/admin/programs/$programId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/settings'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/admin/applications'
    | '/admin/users'
    | '/apply/status'
    | '/matches/$id'
    | '/opportunities/$id'
    | '/profile/agent'
    | '/profile/attendance'
    | '/profile/edit'
    | '/admin/'
    | '/apply/'
    | '/matches/'
    | '/opportunities/'
    | '/orgs/'
    | '/profile/'
    | '/settings/'
    | '/org/$slug/admin'
    | '/admin/opportunities/new'
    | '/admin/users/$userId'
    | '/org/$slug/events'
    | '/org/$slug/join'
    | '/org/$slug/programs'
    | '/org/$slug/visit'
    | '/admin/applications/'
    | '/admin/costs/'
    | '/admin/opportunities/'
    | '/admin/users/'
    | '/org/$slug/'
    | '/admin/opportunities/$id/edit'
    | '/org/$slug/admin/bookings'
    | '/org/$slug/admin/guests'
    | '/org/$slug/admin/settings'
    | '/org/$slug/admin/setup'
    | '/org/$slug/admin/space'
    | '/org/$slug/apply/$opportunityId'
    | '/org/$slug/program/$programSlug'
    | '/org/$slug/space/bookings'
    | '/org/$slug/admin/'
    | '/org/$slug/space/'
    | '/org/$slug/admin/members/$userId'
    | '/org/$slug/poll/$pollToken/$respondentToken'
    | '/org/$slug/survey/$surveyToken/$respondentToken'
    | '/org/$slug/admin/applications/'
    | '/org/$slug/admin/crm/'
    | '/org/$slug/admin/members/'
    | '/org/$slug/admin/opportunities/'
    | '/org/$slug/admin/programs/'
    | '/org/$slug/poll/$pollToken/'
    | '/org/$slug/survey/$surveyToken/'
    | '/org/$slug/admin/opportunities/$oppId/email'
    | '/org/$slug/admin/programs/$programId/session-runner'
    | '/org/$slug/admin/opportunities/$oppId/'
    | '/org/$slug/admin/programs/$programId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApplyRouteRoute: typeof ApplyRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  MatchesIdRoute: typeof MatchesIdRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  ProfileAgentRoute: typeof ProfileAgentRoute
  ProfileAttendanceRoute: typeof ProfileAttendanceRoute
  ProfileEditRoute: typeof ProfileEditRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  OrgsIndexRoute: typeof OrgsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  OrgSlugAdminRouteRoute: typeof OrgSlugAdminRouteRouteWithChildren
  OrgSlugEventsRoute: typeof OrgSlugEventsRoute
  OrgSlugJoinRoute: typeof OrgSlugJoinRoute
  OrgSlugProgramsRoute: typeof OrgSlugProgramsRoute
  OrgSlugVisitRoute: typeof OrgSlugVisitRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugApplyOpportunityIdRoute: typeof OrgSlugApplyOpportunityIdRoute
  OrgSlugProgramProgramSlugRoute: typeof OrgSlugProgramProgramSlugRoute
  OrgSlugSpaceBookingsRoute: typeof OrgSlugSpaceBookingsRoute
  OrgSlugSpaceIndexRoute: typeof OrgSlugSpaceIndexRoute
  OrgSlugPollPollTokenRespondentTokenRoute: typeof OrgSlugPollPollTokenRespondentTokenRoute
  OrgSlugSurveySurveyTokenRespondentTokenRoute: typeof OrgSlugSurveySurveyTokenRespondentTokenRoute
  OrgSlugPollPollTokenIndexRoute: typeof OrgSlugPollPollTokenIndexRoute
  OrgSlugSurveySurveyTokenIndexRoute: typeof OrgSlugSurveySurveyTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/': {
      id: '/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof OrgsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/': {
      id: '/apply/'
      path: '/'
      fullPath: '/apply/'
      preLoaderRoute: typeof ApplyIndexRouteImport
      parentRoute: typeof ApplyRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/attendance': {
      id: '/profile/attendance'
      path: '/profile/attendance'
      fullPath: '/profile/attendance'
      preLoaderRoute: typeof ProfileAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/agent': {
      id: '/profile/agent'
      path: '/profile/agent'
      fullPath: '/profile/agent'
      preLoaderRoute: typeof ProfileAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/status': {
      id: '/apply/status'
      path: '/status'
      fullPath: '/apply/status'
      preLoaderRoute: typeof ApplyStatusRouteImport
      parentRoute: typeof ApplyRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/org/$slug/': {
      id: '/org/$slug/'
      path: '/org/$slug'
      fullPath: '/org/$slug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRouteRoute
    }
    '/admin/opportunities/': {
      id: '/admin/opportunities/'
      path: '/opportunities'
      fullPath: '/admin/opportunities/'
      preLoaderRoute: typeof AdminOpportunitiesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/costs/': {
      id: '/admin/costs/'
      path: '/costs'
      fullPath: '/admin/costs/'
      preLoaderRoute: typeof AdminCostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminApplicationsRouteRoute
    }
    '/org/$slug/visit': {
      id: '/org/$slug/visit'
      path: '/org/$slug/visit'
      fullPath: '/org/$slug/visit'
      preLoaderRoute: typeof OrgSlugVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/programs': {
      id: '/org/$slug/programs'
      path: '/org/$slug/programs'
      fullPath: '/org/$slug/programs'
      preLoaderRoute: typeof OrgSlugProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/join': {
      id: '/org/$slug/join'
      path: '/org/$slug/join'
      fullPath: '/org/$slug/join'
      preLoaderRoute: typeof OrgSlugJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/events': {
      id: '/org/$slug/events'
      path: '/org/$slug/events'
      fullPath: '/org/$slug/events'
      preLoaderRoute: typeof OrgSlugEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRouteRoute
    }
    '/admin/opportunities/new': {
      id: '/admin/opportunities/new'
      path: '/opportunities/new'
      fullPath: '/admin/opportunities/new'
      preLoaderRoute: typeof AdminOpportunitiesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/org/$slug/admin': {
      id: '/org/$slug/admin'
      path: '/org/$slug/admin'
      fullPath: '/org/$slug/admin'
      preLoaderRoute: typeof OrgSlugAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/space/': {
      id: '/org/$slug/space/'
      path: '/org/$slug/space'
      fullPath: '/org/$slug/space/'
      preLoaderRoute: typeof OrgSlugSpaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/admin/': {
      id: '/org/$slug/admin/'
      path: '/'
      fullPath: '/org/$slug/admin/'
      preLoaderRoute: typeof OrgSlugAdminIndexRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/space/bookings': {
      id: '/org/$slug/space/bookings'
      path: '/org/$slug/space/bookings'
      fullPath: '/org/$slug/space/bookings'
      preLoaderRoute: typeof OrgSlugSpaceBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/program/$programSlug': {
      id: '/org/$slug/program/$programSlug'
      path: '/org/$slug/program/$programSlug'
      fullPath: '/org/$slug/program/$programSlug'
      preLoaderRoute: typeof OrgSlugProgramProgramSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/apply/$opportunityId': {
      id: '/org/$slug/apply/$opportunityId'
      path: '/org/$slug/apply/$opportunityId'
      fullPath: '/org/$slug/apply/$opportunityId'
      preLoaderRoute: typeof OrgSlugApplyOpportunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/admin/space': {
      id: '/org/$slug/admin/space'
      path: '/space'
      fullPath: '/org/$slug/admin/space'
      preLoaderRoute: typeof OrgSlugAdminSpaceRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/admin/setup': {
      id: '/org/$slug/admin/setup'
      path: '/setup'
      fullPath: '/org/$slug/admin/setup'
      preLoaderRoute: typeof OrgSlugAdminSetupRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/admin/settings': {
      id: '/org/$slug/admin/settings'
      path: '/settings'
      fullPath: '/org/$slug/admin/settings'
      preLoaderRoute: typeof OrgSlugAdminSettingsRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/admin/guests': {
      id: '/org/$slug/admin/guests'
      path: '/guests'
      fullPath: '/org/$slug/admin/guests'
      preLoaderRoute: typeof OrgSlugAdminGuestsRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/admin/bookings': {
      id: '/org/$slug/admin/bookings'
      path: '/bookings'
      fullPath: '/org/$slug/admin/bookings'
      preLoaderRoute: typeof OrgSlugAdminBookingsRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/admin/opportunities/$id/edit': {
      id: '/admin/opportunities/$id/edit'
      path: '/opportunities/$id/edit'
      fullPath: '/admin/opportunities/$id/edit'
      preLoaderRoute: typeof AdminOpportunitiesIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/org/$slug/survey/$surveyToken/': {
      id: '/org/$slug/survey/$surveyToken/'
      path: '/org/$slug/survey/$surveyToken'
      fullPath: '/org/$slug/survey/$surveyToken/'
      preLoaderRoute: typeof OrgSlugSurveySurveyTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/poll/$pollToken/': {
      id: '/org/$slug/poll/$pollToken/'
      path: '/org/$slug/poll/$pollToken'
      fullPath: '/org/$slug/poll/$pollToken/'
      preLoaderRoute: typeof OrgSlugPollPollTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/admin/programs/': {
      id: '/org/$slug/admin/programs/'
      path: '/programs'
      fullPath: '/org/$slug/admin/programs/'
      preLoaderRoute: typeof OrgSlugAdminProgramsIndexRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/admin/opportunities/': {
      id: '/org/$slug/admin/opportunities/'
      path: '/opportunities'
      fullPath: '/org/$slug/admin/opportunities/'
      preLoaderRoute: typeof OrgSlugAdminOpportunitiesIndexRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/admin/members/': {
      id: '/org/$slug/admin/members/'
      path: '/members'
      fullPath: '/org/$slug/admin/members/'
      preLoaderRoute: typeof OrgSlugAdminMembersIndexRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/admin/crm/': {
      id: '/org/$slug/admin/crm/'
      path: '/crm'
      fullPath: '/org/$slug/admin/crm/'
      preLoaderRoute: typeof OrgSlugAdminCrmIndexRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/admin/applications/': {
      id: '/org/$slug/admin/applications/'
      path: '/applications'
      fullPath: '/org/$slug/admin/applications/'
      preLoaderRoute: typeof OrgSlugAdminApplicationsIndexRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/survey/$surveyToken/$respondentToken': {
      id: '/org/$slug/survey/$surveyToken/$respondentToken'
      path: '/org/$slug/survey/$surveyToken/$respondentToken'
      fullPath: '/org/$slug/survey/$surveyToken/$respondentToken'
      preLoaderRoute: typeof OrgSlugSurveySurveyTokenRespondentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/poll/$pollToken/$respondentToken': {
      id: '/org/$slug/poll/$pollToken/$respondentToken'
      path: '/org/$slug/poll/$pollToken/$respondentToken'
      fullPath: '/org/$slug/poll/$pollToken/$respondentToken'
      preLoaderRoute: typeof OrgSlugPollPollTokenRespondentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$slug/admin/members/$userId': {
      id: '/org/$slug/admin/members/$userId'
      path: '/members/$userId'
      fullPath: '/org/$slug/admin/members/$userId'
      preLoaderRoute: typeof OrgSlugAdminMembersUserIdRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/admin/programs/$programId/': {
      id: '/org/$slug/admin/programs/$programId/'
      path: '/programs/$programId'
      fullPath: '/org/$slug/admin/programs/$programId/'
      preLoaderRoute: typeof OrgSlugAdminProgramsProgramIdIndexRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/admin/opportunities/$oppId/': {
      id: '/org/$slug/admin/opportunities/$oppId/'
      path: '/opportunities/$oppId'
      fullPath: '/org/$slug/admin/opportunities/$oppId/'
      preLoaderRoute: typeof OrgSlugAdminOpportunitiesOppIdIndexRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/admin/programs/$programId/session-runner': {
      id: '/org/$slug/admin/programs/$programId/session-runner'
      path: '/programs/$programId/session-runner'
      fullPath: '/org/$slug/admin/programs/$programId/session-runner'
      preLoaderRoute: typeof OrgSlugAdminProgramsProgramIdSessionRunnerRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
    '/org/$slug/admin/opportunities/$oppId/email': {
      id: '/org/$slug/admin/opportunities/$oppId/email'
      path: '/opportunities/$oppId/email'
      fullPath: '/org/$slug/admin/opportunities/$oppId/email'
      preLoaderRoute: typeof OrgSlugAdminOpportunitiesOppIdEmailRouteImport
      parentRoute: typeof OrgSlugAdminRouteRoute
    }
  }
}

interface AdminApplicationsRouteRouteChildren {
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
}

const AdminApplicationsRouteRouteChildren: AdminApplicationsRouteRouteChildren =
  {
    AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
  }

const AdminApplicationsRouteRouteWithChildren =
  AdminApplicationsRouteRoute._addFileChildren(
    AdminApplicationsRouteRouteChildren,
  )

interface AdminUsersRouteRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteRouteChildren: AdminUsersRouteRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteRouteWithChildren = AdminUsersRouteRoute._addFileChildren(
  AdminUsersRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminApplicationsRouteRoute: typeof AdminApplicationsRouteRouteWithChildren
  AdminUsersRouteRoute: typeof AdminUsersRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOpportunitiesNewRoute: typeof AdminOpportunitiesNewRoute
  AdminCostsIndexRoute: typeof AdminCostsIndexRoute
  AdminOpportunitiesIndexRoute: typeof AdminOpportunitiesIndexRoute
  AdminOpportunitiesIdEditRoute: typeof AdminOpportunitiesIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApplicationsRouteRoute: AdminApplicationsRouteRouteWithChildren,
  AdminUsersRouteRoute: AdminUsersRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminOpportunitiesNewRoute: AdminOpportunitiesNewRoute,
  AdminCostsIndexRoute: AdminCostsIndexRoute,
  AdminOpportunitiesIndexRoute: AdminOpportunitiesIndexRoute,
  AdminOpportunitiesIdEditRoute: AdminOpportunitiesIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApplyRouteRouteChildren {
  ApplyStatusRoute: typeof ApplyStatusRoute
  ApplyIndexRoute: typeof ApplyIndexRoute
}

const ApplyRouteRouteChildren: ApplyRouteRouteChildren = {
  ApplyStatusRoute: ApplyStatusRoute,
  ApplyIndexRoute: ApplyIndexRoute,
}

const ApplyRouteRouteWithChildren = ApplyRouteRoute._addFileChildren(
  ApplyRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface OrgSlugAdminRouteRouteChildren {
  OrgSlugAdminBookingsRoute: typeof OrgSlugAdminBookingsRoute
  OrgSlugAdminGuestsRoute: typeof OrgSlugAdminGuestsRoute
  OrgSlugAdminSettingsRoute: typeof OrgSlugAdminSettingsRoute
  OrgSlugAdminSetupRoute: typeof OrgSlugAdminSetupRoute
  OrgSlugAdminSpaceRoute: typeof OrgSlugAdminSpaceRoute
  OrgSlugAdminIndexRoute: typeof OrgSlugAdminIndexRoute
  OrgSlugAdminMembersUserIdRoute: typeof OrgSlugAdminMembersUserIdRoute
  OrgSlugAdminApplicationsIndexRoute: typeof OrgSlugAdminApplicationsIndexRoute
  OrgSlugAdminCrmIndexRoute: typeof OrgSlugAdminCrmIndexRoute
  OrgSlugAdminMembersIndexRoute: typeof OrgSlugAdminMembersIndexRoute
  OrgSlugAdminOpportunitiesIndexRoute: typeof OrgSlugAdminOpportunitiesIndexRoute
  OrgSlugAdminProgramsIndexRoute: typeof OrgSlugAdminProgramsIndexRoute
  OrgSlugAdminOpportunitiesOppIdEmailRoute: typeof OrgSlugAdminOpportunitiesOppIdEmailRoute
  OrgSlugAdminProgramsProgramIdSessionRunnerRoute: typeof OrgSlugAdminProgramsProgramIdSessionRunnerRoute
  OrgSlugAdminOpportunitiesOppIdIndexRoute: typeof OrgSlugAdminOpportunitiesOppIdIndexRoute
  OrgSlugAdminProgramsProgramIdIndexRoute: typeof OrgSlugAdminProgramsProgramIdIndexRoute
}

const OrgSlugAdminRouteRouteChildren: OrgSlugAdminRouteRouteChildren = {
  OrgSlugAdminBookingsRoute: OrgSlugAdminBookingsRoute,
  OrgSlugAdminGuestsRoute: OrgSlugAdminGuestsRoute,
  OrgSlugAdminSettingsRoute: OrgSlugAdminSettingsRoute,
  OrgSlugAdminSetupRoute: OrgSlugAdminSetupRoute,
  OrgSlugAdminSpaceRoute: OrgSlugAdminSpaceRoute,
  OrgSlugAdminIndexRoute: OrgSlugAdminIndexRoute,
  OrgSlugAdminMembersUserIdRoute: OrgSlugAdminMembersUserIdRoute,
  OrgSlugAdminApplicationsIndexRoute: OrgSlugAdminApplicationsIndexRoute,
  OrgSlugAdminCrmIndexRoute: OrgSlugAdminCrmIndexRoute,
  OrgSlugAdminMembersIndexRoute: OrgSlugAdminMembersIndexRoute,
  OrgSlugAdminOpportunitiesIndexRoute: OrgSlugAdminOpportunitiesIndexRoute,
  OrgSlugAdminProgramsIndexRoute: OrgSlugAdminProgramsIndexRoute,
  OrgSlugAdminOpportunitiesOppIdEmailRoute:
    OrgSlugAdminOpportunitiesOppIdEmailRoute,
  OrgSlugAdminProgramsProgramIdSessionRunnerRoute:
    OrgSlugAdminProgramsProgramIdSessionRunnerRoute,
  OrgSlugAdminOpportunitiesOppIdIndexRoute:
    OrgSlugAdminOpportunitiesOppIdIndexRoute,
  OrgSlugAdminProgramsProgramIdIndexRoute:
    OrgSlugAdminProgramsProgramIdIndexRoute,
}

const OrgSlugAdminRouteRouteWithChildren =
  OrgSlugAdminRouteRoute._addFileChildren(OrgSlugAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApplyRouteRoute: ApplyRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  MatchesIdRoute: MatchesIdRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  ProfileAgentRoute: ProfileAgentRoute,
  ProfileAttendanceRoute: ProfileAttendanceRoute,
  ProfileEditRoute: ProfileEditRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  OrgsIndexRoute: OrgsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  OrgSlugAdminRouteRoute: OrgSlugAdminRouteRouteWithChildren,
  OrgSlugEventsRoute: OrgSlugEventsRoute,
  OrgSlugJoinRoute: OrgSlugJoinRoute,
  OrgSlugProgramsRoute: OrgSlugProgramsRoute,
  OrgSlugVisitRoute: OrgSlugVisitRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugApplyOpportunityIdRoute: OrgSlugApplyOpportunityIdRoute,
  OrgSlugProgramProgramSlugRoute: OrgSlugProgramProgramSlugRoute,
  OrgSlugSpaceBookingsRoute: OrgSlugSpaceBookingsRoute,
  OrgSlugSpaceIndexRoute: OrgSlugSpaceIndexRoute,
  OrgSlugPollPollTokenRespondentTokenRoute:
    OrgSlugPollPollTokenRespondentTokenRoute,
  OrgSlugSurveySurveyTokenRespondentTokenRoute:
    OrgSlugSurveySurveyTokenRespondentTokenRoute,
  OrgSlugPollPollTokenIndexRoute: OrgSlugPollPollTokenIndexRoute,
  OrgSlugSurveySurveyTokenIndexRoute: OrgSlugSurveySurveyTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
